<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

</body>
</html>

<script type="text/javascript">
    // ——————————————————————01.  ——————————————————————————
    // ——————————————————————01.  Promise 的含义——————————————————————————
    // Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。它由社区最早提出和实现，ES6 将其写进了语言标准，统一了用法，原生提供了Promise对象。
    // Promise实例
    //    {
    //        const promise = new Promise(function (resolve, reject) {
    //            // ... some code
    //            if (/* 异步操作成功 */) {
    //                resolve(value);
    //            } else {
    //                reject(error);
    //            }
    //        });
    //    }

    // 举个栗子
    //    {
    //
    //        let promiss = new Promise(function (resolve, reject) {
    //            setTimeout(function () {
    //                resolve('1s后执行了');
    //            }, 1000)
    //        });
    //
    //        promiss.then((res) => {
    //            console.log(res)
    //        })
    //    }


    // 执行顺序
    //    {
    //        new Promise((resolve, reject) => {
    //            console.log('resolve')
    //            resolve()
    //        })
    //            .then(res => {
    //                console.log('success')
    //            });
    //        console.log('普通的console')
    //        //resolve
    //        //普通的console
    //        // success
    //    }


    // 异步加载图片的实例
    //    {
    //        function loadImage(url) {
    //            return new Promise(function (resolve, reject) {
    //                const image = new Image();
    //                image.onload = function () {
    //                    // 说明加载成功
    //                    resolve('图片加载成功了');
    //                }
    //                image.onerror = function () {
    //                    // 说明加载失败
    //                    reject(new Error('图片加载失败'));
    //                }
    //                image.src = url;
    //            })
    //        }
    //        loadImage('https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1561367381&di=768decee7422fcf22524c49fb98f4ab3&imgtype=jpg&er=1&src=http%3A%2F%2Fwww.qqoi.cn%2Fimg_bizhi%2F245213297.jpeg')
    //            .then(res => {
    //                console.log(res);
    //            }, err => {
    //                console.log(err)
    //            })
    //    }


    // 异步请求网络数据
    //    {
    //        const getJSON = function (url) {
    //            const promise = new Promise(function (resolve, reject) {
    //                const handler = function () {
    //                    if (this.readyState !== 4) {
    //                        return;
    //                    }
    //                    if (this.status === 200) {
    //                        resolve(this.response);
    //                    } else {
    //                        reject(new Error(this.statusText));
    //                    }
    //                };
    //                const client = new XMLHttpRequest();
    //                client.open("GET", url);
    //                client.onreadystatechange = handler;
    //                client.responseType = "text";
    //                client.setRequestHeader("Accept", "application/text");
    //                client.send();
    //
    //            });
    //
    //            return promise;
    //        };
    //
    //        getJSON('http://www.originoo.com/ws/p.index.php').then(function (res) {
    //            console.log(res);
    //        }, function (error) {
    //            console.error('出错了', error);
    //        });
    //    }


    //    {
    //        const p1 = new Promise((resolve, reject) => {
    //            console.log('p1执行了')
    //            setTimeout(() => {
    //                reject(new Error('出现错误了'));
    //            }, 3000)
    //        })
    //
    //        new Promise((resolve, reject) => {
    //            console.log('p2执行了')
    //            resolve(p1);
    //        })
    //            .then(res => {
    //                console.log('结果', res)
    //            })
    //            .catch(e => {
    //                console.log(e)
    //            })
    //    }


    // ——————————————————————04. Promise.prototype.catch()——————————————————————————
    // Promise.prototype.catch方法是.then(null, rejection)或.then(undefined, rejection)的别名，用于指定发生错误时的回调函数。
    //    {
    //        new Promise((resolve, reject) => {
    //            reject('出错啦1111')
    //        })
    //            .then(res => {
    //                console.log('success', res)
    //            }, err => {
    //                console.log('failed', err)   // 会走此方法
    //            })
    //            .catch(e => {
    //                console.log('catch', e)
    //            })
    //
    //
    //        new Promise((resolve, reject) => {
    //            reject('出错啦222')
    //        })
    //            .then(res => {
    //                console.log('success', res)
    //            }, err => {
    //                console.log('failed', err)   // 会走此方法
    //            })
    //            .catch(e => {
    //                console.log('catch', e)
    //            })
    //    }

    // 如果 Promise 状态已经变成resolved，再抛出错误是无效的。

    //    {
    //        new Promise((resolve, reject) => {
    //            resolve('hhhh');
    //            throw  new Error('发生异常了');
    //        })
    //            .then(res => {
    //                console.log(res)   // hhhh
    //            })
    //            .catch(err => {
    //                console.log(err)
    //            })
    //    }

    // 一般来说，不要在then方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法。
    //    {
    //        let promise = new Promise((resolve, reject) => {
    //            throw new Error('明天再也没有你的笑脸');
    //        });
    //        // 不推荐
    //        promise
    //            .then(res => {
    //                console.log('success', res)
    //            }, error => {
    //                console.log('error', error)
    //            })
    //
    //        // 推荐
    //        promise
    //            .then(res => {
    //                console.log('success', res)
    //            })
    //            .catch(err => {
    //                console.error(err)
    //            })
    //    }

    // 第二种写法可以捕获前面then方法执行中的错误，也更接近同步的写法（try/catch）。因此，建议总是使用catch方法，而不使用then方法的第二个参数。


    // 如果没有使用catch方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。
    //    {
    //        let promise = function () {
    //            return new Promise((resolve, reject) => {
    //                resolve(x + 1);
    //            });
    //        }
    //        promise().then(res => {
    //            console.log(res)
    //        })
    //        setTimeout(function () {
    //            console.log('运行了')
    //        }, 1000)
    //    }
    /*会打印出错误提示ReferenceError: x is not defined，
     但是不会退出进程、终止脚本执行，2 秒之后还是会输出123。
     这就是说，Promise 内部的错误不会影响到 Promise 外部的代码，
     通俗的说法就是“Promise 会吃掉错误”。*/



    // ——————————————————————05. Promise.prototype.finally() ——————————————————————————
    //finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。
    //    {
    //        new Promise((resolve, reject) => {
    //            resolve('成功了');
    //        }).then(res => {
    //            console.log(res)
    //        }).catch(err => {
    //            console.log(err)
    //        }).finally(() => {
    //            console.log('执行了finally')
    //        });
    //    }


    // ——————————————————————06. Promise.all()——————————————————————————
    // Promise.all方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
    //    {
    //        const promises = [1, 2, 3, 4, 5, 6].map(function (item) {
    //            return new Promise((resolve, reject) => {
    //                resolve(Math.pow(item, 2));
    //            })
    //        })
    //        Promise.all(promises)
    //            .then(res => {
    //                console.log('success', res)  // 返回的是一个数组，且只执行一次
    //            })
    //            .catch(err => {
    //                console.error(err)
    //            })
    //    }


    //        {
    //            const databasePromise = function (promise) {
    //                return new Promise((resolve, reject) => {
    //                    // 连接数据库成功  获取用户名
    //                    resolve(promise);
    //                })
    //            };
    //            const weatherData = databasePromise(new Promise((resolve, reject) => {
    //                resolve('获取天气信息成功');
    //            }));
    //            const userInfo = databasePromise(new Promise((resolve, reject) => {
    //                resolve('获取用户信息成功');
    //            }));
    //            Promise.all([weatherData, userInfo])
    //                .then(([weather, user]) => {
    //                        console.log('success', weather, user)
    //                    }
    //                )
    //                .catch(err => {
    //                    console.log(err)
    //                })
    //        }


    // 如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。
    //        {
    //            let p1 = new Promise((resolve, reject) => {
    //                resolve(x+1);
    //            })
    //                .then(res => res)
    //                .catch(err => {
    //                    console.log('p1', err)
    //                })
    //
    //            let p2 = new Promise((resolve, reject) => {
    //                resolve(x+1);
    //            })
    //                .then(res => res)
    //                .catch(err => {
    //                    console.log('p2', err)
    //                });
    //
    //            Promise.all([p1, p2])
    //                .then(res => {
    //                    console.log('all', res)
    //                })
    //                .catch(err => {
    //                    console.log('all', err)
    //                })
    //        }


    //    {
    //        let connectDatabase = function () {
    //            return new Promise((resolve, reject) => {
    //                resolve(true)
    //            })
    //        }
    //
    //        let weather = connectDatabase()
    //            .then(res => new Promise((resolve, reject) => {
    //                resolve("获取天气信息成功");
    //            }))
    //
    //        let user = connectDatabase()
    //            .then(res => new Promise((resolve, reject) => {
    //                resolve('获取用户信息成功');
    //            }));
    //
    //        Promise.all([weather, user])
    //            .then(([weather, user]) => {
    //                console.log('all', [weather, user])
    //            })
    //    }

    // 如果p2没有自己的catch方法，就会调用Promise.all()的catch方法。
    //    {
    //        let p1 = new Promise((resolve, reject) => {
    //            resolve('Hello');
    //        }).then(res => res)
    //            .catch(err => {
    //                console.log('p1', err)
    //            });
    //        let p2 = new Promise((resolve, reject) => {
    //            reject(new Error('p2出错了'));
    //        })
    //            .then(res => res);
    //
    //
    //        Promise.all([p1, p2])
    //            .then(res => {
    //                console.log(res)
    //            })
    //            .catch(err => {
    //                console.log('all', err)
    //            })
    //    }


    // ——————————————————————07. Promise.race()——————————————————————————
    // Promise.race方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。
    // {
    //     const p = Promise.race([
    //         fetch('https://www.baidu.com'),
    //         new Promise(function (resolve, reject) {
    //             setTimeout(() => reject(new Error('request timeout')), 5000)
    //         })
    //     ]);
    //     p
    //         .then(console.log)
    //         .catch(console.error);
    // }


    // 只响应一个
    // {
    //     Promise.race([
    //         new Promise((resolve, reject) => {
    //             setTimeout(function () {
    //                 resolve('第一个');
    //             }, 3000)
    //         }),
    //         new Promise((resolve, reject) => {
    //             setTimeout(function () {
    //                 resolve('第二个');
    //             }, 1000)
    //         })
    //     ])
    //         .then(console.log)
    // }


    // ——————————————————————08. Promise.resolve()——————————————————————————
    // 有时需要将现有对象转为 Promise 对象，Promise.resolve方法就起到这个作用。
    // Promise.resolve等价于下面的写法。
    // {
    //     Promise.resolve('foo')
    //     // 等价于
    //     new Promise(resolve => resolve('foo'))
    // }

    // （1）参数是一个 Promise 实例
    // （2）参数是一个thenable对象(有then方法的对象)

    // {
    //     let thenable1 = {
    //         then: function () {
    //             console.log('对象中的then方法')
    //         }
    //     };
    //
    //     Promise.resolve(thenable1)
    //         .then(res => {
    //             console.log('res', res)
    //         })
    //
    //     let thenable2 = {
    //         then: function (resolve, reject) {
    //             resolve('thenable2中的then方法')
    //         }
    //     };
    //
    //     Promise.resolve(thenable2)
    //         .then(res => {
    //             console.log('res', res)
    //         })
    // }


</script>